version: '3'

services:
  mc:
    image: itzg/minecraft-server
    environment:
      EULA: "true"
      TYPE: "FORGE"
      DEBUG: "true"
      MEMORY: "15G"
      DIFFICULTY: "hard"
      MAX_PLAYERS: "10"
      MOTD: "Minecraft Rondón"
      FORGE_VERSION: "47.2.18"
      VERSION: "1.20.1"
      FORGE_FORCE_REINSTALL: "false"
      ONLINE_MODE: "false"
      VIEW_DISTANCE: "10"
      ENTITY_BROADCAST_RANGE_PERCENTAGE: "100"
      OPS: "Rondon"
      ENABLE_RCON: "true"
      RCON_PASSWORD: "password"
      RCON_PORT: "8000"
    restart: unless-stopped
    ports:
      - "25565:25565"
      - "8000:8000"
    volumes:
      - ./data:/data
  monitor:
    image: itzg/mc-monitor
    command: export-for-prometheus
    environment:
      EXPORT_SERVERS: mc
      DEBUG: "true"
    depends_on:
      - mc
  cadvisor:
    image: gcr.io/cadvisor/cadvisor
    ports:
      - "8180:8080"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-tsdb:/prometheus
    depends_on:
      - monitor
  grafana:
    image: grafana/grafana:10.0.0
    environment:
      GF_AUTH_DISABLE_LOGIN_FORM: "false"
      GF_AUTH_ANONYMOUS_ENABLED: "true"
      GF_AUTH_ANONYMOUS_ORG_NAME: "minecraft"
      GF_AUTH_ANONYMOUS_ORG_ROLE: "minecraft"
      GF_USERS_ALLOW_SIGN_UP: "false"
      GF_SECURITY_ADMIN_PASSWORD: "password"
    ports:
      - "3000:3000"
    volumes:
      - grafana-lib:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./dashboards:/etc/grafana/dashboards
    depends_on:
      - prometheus


volumes:
  mc-data: {}
  prometheus-tsdb: {}
  grafana-lib: {}
